<a href="https://colab.research.google.com/github/Geek-a-Byte/thesis/blob/main/Step_3_Split_into_5_training_datasets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import random
import cv2
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2' 
from imutils import paths
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer
from sklearn.model_selection import train_test_split
from sklearn.utils import shuffle
from sklearn.metrics import accuracy_score

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!unzip "/content/drive/MyDrive/CervicalCancerTrainDataset.zip" -d "./CervicalCancerTrainingDataset/"

In [ ]:
def load(paths, verbose=-1):
    '''expects images for each class in seperate dir'''
    data = list()
    labels = list()
    # loop over the input images
    for (i, imgpath) in enumerate(paths):
        # load the image and extract the class labels
        im_gray = cv2.imread(imgpath, cv2.IMREAD_GRAYSCALE)
        image = np.array(im_gray).flatten()
        label = imgpath.split(os.path.sep)[-2] # Metaplastic, Parabasal, Koilocytotic, Superficial-Intermediate, Dyskeratotic
        # scale the image to [0, 1] and add to list
        data.append(image/255)
        labels.append(label)
        # show an update every `verbose` images
        if verbose > 0 and i > 0 and (i + 1) % verbose == 0:
            print(label);
            print("[INFO] processed {}/{}".format(i + 1, len(paths)))
    # return a tuple of the data and labels
    return data, labels

In [ ]:
#declear path to your data folder
img_path = '/content/CervicalCancerTrainingDataset'

#get the path list using the path object
image_paths = list(paths.list_images(img_path))

#apply our function
image_list, label_list = load(image_paths, verbose=10000)

In [ ]:
a,b,c = np.random.randint(0,10,[3,4])

print(a)
print(b)
print(c)


[4 5 3 2]
[9 3 8 9]
[4 5 9 2]


In [ ]:
# Function for Creating Train / Validation / Test folders (One time use Only)
import shutil
def TrainSplitting(root_dir, classes_dir, main = "", val_ratio = 0.15, test_ratio = 0.15):
    for cls in classes_dir:
        # Creating Split Folders
        os.makedirs('Client_1/' + cls)
        os.makedirs('Client_2/' + cls)
        os.makedirs('Client_3/' + cls)
        os.makedirs('Client_4/' + cls)
        os.makedirs('Client_5/' + cls)
        
        # Folder to copy images from
        src = os.path.join(root_dir, cls, main);

        # Spliting the Files in the Given ratio
        allFileNames = os.listdir(src)
        np.random.shuffle(allFileNames)

        div=0.2
        div_data_1=int(len(allFileNames)*(1-(div*4)));
        div_data_2=int(len(allFileNames)*(1-(div*3)));
        div_data_3=int(len(allFileNames)*(1-(div*2)));
        div_data_4=int(len(allFileNames)*(1-(div)));

        # print(div_data_1)
        # print(div_data_2)
        # print(div_data_3)
        # print(div_data_4)

        client1_FileNames, client2_FileNames, client3_FileNames, client4_FileNames, client5_FileNames = np.split(np.array(allFileNames), [div_data_1,div_data_2,div_data_3,div_data_4])

        client1_FileNames = [src+'/'+ name for name in client1_FileNames.tolist()]
        client2_FileNames = [src+'/' + name for name in client2_FileNames.tolist()]
        client3_FileNames = [src+'/' + name for name in client3_FileNames.tolist()]
        client4_FileNames = [src+'/' + name for name in client4_FileNames.tolist()]
        client5_FileNames = [src+'/' + name for name in client5_FileNames.tolist()]

        # Printing the Split Details
        print(cls,':')
        print('Total images: ', len(allFileNames))
        print('Client_1: ', len(client1_FileNames))
        print('Client_2: ', len(client2_FileNames))
        print('Client_3: ', len(client3_FileNames))
        print('Client_4: ', len(client4_FileNames))
        print('Client_5: ', len(client5_FileNames))

        # Copy-pasting images
        for name in client1_FileNames:
            shutil.copy(name, 'Client_1/' + cls)

        for name in client2_FileNames:
            shutil.copy(name, 'Client_2/' + cls)

        for name in client3_FileNames:
            shutil.copy(name, 'Client_3/' + cls)

        for name in client4_FileNames:
            shutil.copy(name, 'Client_4/' + cls)

        for name in client5_FileNames:
            shutil.copy(name, 'Client_5/' + cls)
        print();
        

# Preforming Train / Validation / Test Split
root_dir = "/content/CervicalCancerTrainingDataset/CervicalCancerTrainDataset"               # Dataset Root Folder
classes_dir = ["Dyskeratotic", "Koilocytotic", "Metaplastic", "Parabasal", "Superficial-Intermediate"]   # Classes
TrainSplitting(root_dir, classes_dir);

Dyskeratotic :
Total images:  813
Client_1:  162
Client_2:  163
Client_3:  162
Client_4:  163
Client_5:  163

Koilocytotic :
Total images:  825
Client_1:  164
Client_2:  165
Client_3:  166
Client_4:  165
Client_5:  165

Metaplastic :
Total images:  793
Client_1:  158
Client_2:  159
Client_3:  158
Client_4:  159
Client_5:  159

Parabasal :
Total images:  787
Client_1:  157
Client_2:  157
Client_3:  158
Client_4:  157
Client_5:  158

Superficial-Intermediate :
Total images:  831
Client_1:  166
Client_2:  166
Client_3:  166
Client_4:  166
Client_5:  167



In [ ]:
#@title **Utility to zip and download a directory**
#@markdown Use this method to zip and download a directory. For ex. a TB logs 
#@markdown directory or a checkpoint(s) directory.

from google.colab import files
import os

dir_to_zip = '/content/Client_5' #@param {type: "string"}
output_filename = 'Client5_train.zip' #@param {type: "string"}
delete_dir_after_download = "No"  #@param ['Yes', 'No']

os.system( "zip -r {} {}".format( output_filename , dir_to_zip ) )

if delete_dir_after_download == "Yes":
    os.system( "rm -r {}".format( dir_to_zip ) )

files.download( output_filename )

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>